language: node_js
node_js:
  - node

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "Test"
      install: npm install
      script: npm run test:unit

    - stage: deploy
      name: "Deploy"
      install: npm install
      script: npm run build
      deploy:
        provider: s3
        access_key_id: ${AWS_KEY}
        secret_access_key: ${AWS_SECRET_KEY}
        bucket: "beer-site-533-bucket"
        skip_cleanup: true
        upload-dir: client
        local_dir: dist
      if: branch = master
