version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  build-deploy:  
    jobs:
      - test
      - build-deploy:
          requires:
            - test
          filters:
            branches:
              only: master

jobs:
  test:  
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-npm: true
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run tests
          command: npm run test:unit
      
      # - store_artifacts:
      #     path: test-reports/
      #     destination: tr1
      # - store_test_results:
      #     path: test-reports/

  build-deploy:
    docker:
      - image: 'cimg/base:stable'
        environment:
          VUE_APP_API_URL: /api
    steps:
      - checkout
      - node/install:
          install-npm: true
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Deploy Master to Heroku
          command: |
            sh deploy.sh ${EC2_USER}@${EC2_IP}



# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
# version: 2.1

# orbs:
#   node: circleci/node@4.1
#   aws-s3: circleci/aws-s3@2.0

# workflows:
#   sample:
#     jobs:
#       - node/test:
#           version: '15.1'
#           # after the node/test job completes, build the dist packages and save them to a workspace
#           post-steps:
#             - run: npm run build
#             - aws-s3/copy:
#                 from: dist/
#                 to: s3://sample-app-vue
#                 arguments: --recursive